import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, it, expect } from 'vitest';

import { PRE_RENDERED_STATIC_ROUTES } from '../../src/data/site-routes';

// public/robots.txt is a static asset — no build step touches it and nothing
// imported it, so until this file existed the only way to check it was to fetch
// the deployed copy. That is how it came to contradict itself: the repo file
// said `Allow: /` for GPTBot and ClaudeBot while Cloudflare's managed block,
// prepended at the edge, said `Disallow: /` for the same two. Under RFC 9309
// §2.2.2 an `Allow` beats an equally-specific `Disallow`, so the repo file was
// winning and the AI crawlers were let in.
//
// Two things are asserted here, and only the second is about crawlers:
//   1. the file states the intended policy;
//   2. it does not contradict sitemap.xml — advertising a URL for crawling in
//      one file while forbidding it in the other is a Search Console error, and
//      the two files are generated by completely separate code paths.

// vitest runs with the project root as cwd (see vitest.config.ts).
const ROBOTS = readFileSync(resolve(process.cwd(), 'public/robots.txt'), 'utf8');

interface Group {
  agents: string[];
  rules: { allow: boolean; path: string }[];
}

/**
 * Parse robots.txt into groups, per RFC 9309 §2.2.1: consecutive `User-agent`
 * lines accumulate into one group, and the first rule line closes the set.
 */
function parseGroups(source: string): Group[] {
  const groups: Group[] = [];
  let current: Group | null = null;
  let collectingAgents = false;

  for (const raw of source.split('\n')) {
    const line = raw.replace(/#.*$/, '').trim();
    if (!line) continue;
    const [rawField, ...rest] = line.split(':');
    const field = rawField.trim().toLowerCase();
    const value = rest.join(':').trim();

    if (field === 'user-agent') {
      if (!collectingAgents || !current) {
        current = { agents: [], rules: [] };
        groups.push(current);
        collectingAgents = true;
      }
      current.agents.push(value.toLowerCase());
      continue;
    }
    if (field === 'allow' || field === 'disallow') {
      collectingAgents = false;
      current?.rules.push({ allow: field === 'allow', path: value });
    }
    // Sitemap and Content-Signal are not rules; they are checked separately.
  }
  return groups;
}

const GROUPS = parseGroups(ROBOTS);

/** The single group a crawler obeys: its own if it has one, else `*`. */
function groupFor(agent: string): Group | undefined {
  const token = agent.toLowerCase();
  return (
    GROUPS.find((g) => g.agents.includes(token)) ??
    GROUPS.find((g) => g.agents.includes('*'))
  );
}

/** RFC 9309 §2.2.2: longest match wins; `Allow` wins a tie. */
function isAllowed(agent: string, path: string): boolean {
  const group = groupFor(agent);
  if (!group) return true;

  let best: { allow: boolean; length: number } | null = null;
  for (const rule of group.rules) {
    if (rule.path === '') continue; // an empty Disallow permits everything
    const pattern = new RegExp(
      `^${rule.path.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*')}`,
    );
    if (!pattern.test(path)) continue;
    const length = rule.path.length;
    if (!best || length > best.length || (length === best.length && rule.allow)) {
      best = { allow: rule.allow, length };
    }
  }
  return best ? best.allow : true;
}

// Cloudflare's managed AI-crawler block, as served on 2026-08-11. Duplicated
// here on purpose: the test cannot fetch the edge, and the bug was this file
// disagreeing with that list. If Cloudflare's list grows, this one may lag —
// but it can never again silently permit something the edge blocks.
const CLOUDFLARE_MANAGED_BLOCK = [
  'Amazonbot',
  'Applebot-Extended',
  'Bytespider',
  'CCBot',
  'ClaudeBot',
  'CloudflareBrowserRenderingCrawler',
  'Google-Extended',
  'GPTBot',
  'meta-externalagent',
];

// Crawlers whose whole job is to send a reader here. Blocking any of these
// costs traffic or breaks a share card, so each one is an explicit expectation.
const MUST_STAY_WELCOME = [
  'Googlebot',
  'Bingbot',
  'DuckDuckBot',
  'Applebot',
  'Twitterbot',
  'facebookexternalhit',
  'LinkedInBot',
  'WhatsApp',
  'Slackbot-LinkExpanding',
  'TelegramBot',
  // Fires when a person pastes a link, not on a crawl. See the file's comment.
  'ChatGPT-User',
];

describe('public/robots.txt', () => {
  it('parses into groups well enough for the assertions below to mean anything', () => {
    // Without this, a parser that matched nothing would make every test pass.
    expect(GROUPS.length).toBeGreaterThanOrEqual(2);
    expect(GROUPS.flatMap((g) => g.agents).length).toBeGreaterThan(15);
    expect(GROUPS.some((g) => g.agents.includes('*'))).toBe(true);
  });

  it.each(CLOUDFLARE_MANAGED_BLOCK)(
    'does not re-admit %s, which Cloudflare blocks at the edge',
    (agent) => {
      expect(
        isAllowed(agent, '/'),
        `${agent} is blocked by Cloudflare's managed block. Allowing it here ` +
          `does not just duplicate a rule — under RFC 9309 §2.2.2 the Allow ` +
          `wins the tie and the crawler is let in.`,
      ).toBe(false);
    },
  );

  it.each(MUST_STAY_WELCOME)('keeps %s able to reach the site', (agent) => {
    expect(isAllowed(agent, '/'), `${agent} can no longer fetch /`).toBe(true);
    expect(isAllowed(agent, '/case/1234'), `${agent} can no longer fetch a case`).toBe(true);
  });

  it('has no named group granting blanket access, which would bypass the site-wide rules', () => {
    // A crawler obeys exactly one group and does not inherit `*`, so a named
    // `Allow: /` group exempts that crawler from every Disallow in `*`.
    for (const group of GROUPS) {
      if (group.agents.includes('*')) continue;
      const blanket = group.rules.find((r) => r.allow && r.path === '/');
      expect(
        blanket,
        `group [${group.agents.join(', ')}] grants Allow: / — that crawler ` +
          `stops obeying the Disallow rules in the * group.`,
      ).toBeUndefined();
    }
  });

  it('keeps non-public surfaces out of the crawl', () => {
    for (const path of ['/admin/', '/admin/cases', '/portal/', '/updates/preview', '/embed/case/1']) {
      expect(isAllowed('Googlebot', path), `${path} is crawlable`).toBe(false);
    }
  });

  // The real cross-file invariant. sitemap.xml is generated from these routes by
  // scripts/sitemap.ts, which has no idea robots.txt exists.
  it('does not forbid any URL the sitemap advertises', () => {
    const advertised = PRE_RENDERED_STATIC_ROUTES.filter((r) => !r.excludeFromSitemap);
    expect(advertised.length).toBeGreaterThan(10);

    for (const route of advertised) {
      expect(
        isAllowed('Googlebot', route.path),
        `sitemap.xml advertises ${route.path} but robots.txt forbids crawling ` +
          `it. Pick one: drop the Disallow, or set excludeFromSitemap on the ` +
          `route in src/data/site-routes.ts.`,
      ).toBe(true);
    }
  });

  it('points at the sitemap with an absolute URL', () => {
    const sitemaps = [...ROBOTS.matchAll(/^\s*Sitemap:\s*(\S+)\s*$/gim)].map((m) => m[1]);
    expect(sitemaps).toEqual(['https://jawafdehi.org/sitemap.xml']);
  });

  it('states the machine-readable content signal', () => {
    expect(ROBOTS).toMatch(/^Content-Signal:\s*search=yes,ai-train=no,use=reference$/m);
  });
});
